# Run the FastAPI server with prometheus monitoring
run:
    uv run uvicorn server:app --loop server:loop_factory --port 1441

# Create traffic to test the monitoring
create-traffic:
    uv run python create_traffic.py