name: Lint peripherals

on: pull_request

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  GROUPS: stress_test,code_quality,examples

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.11" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install dependencies
        run: just install $GROUPS

      - name: Lint stress test code
        run: just lint stress_tests

      - name: Lint tests code
        run: just lint tests

      - name: Lint tests examples
        run: just lint examples